"use client";
import type { Metadata } from "next";
import { Comfortaa, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer/page";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const comfortaa = Comfortaa({ subsets: ["latin"], weight: "700" });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
