import type { Metadata } from "next";
import { Comfortaa, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });
const comfortaa = Comfortaa({ subsets: ["latin"], weight: "700" });
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export { metadata };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
