import { Metadata } from "next";
import React from "react";
const metadata: Metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

export { metadata };

export default function Contact() {
  return <div>contact us</div>;
}
