import { Metadata } from "next";
import React from "react";
const metadata: Metadata = {
  title: "About us",
  description: "Generated by create next app",
};

export { metadata };

export default function About() {
  return <div>about us</div>;
}
