import { Metadata } from "next";
import React from "react";
const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export { metadata };
export default function Home() {
  return <div>Home</div>;
}
